# Generated by Django 2.2.5 on 2019-11-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Chat member', 'verbose_name_plural': 'Chat members'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_joined',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
