# Generated by Django 2.2.5 on 2019-11-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_member_booleanfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='BooleanField',
            new_name='is_owner',
        ),
    ]
