# Generated by Django 2.2.5 on 2019-11-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191120_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='is_owner',
            new_name='is_creator',
        ),
    ]
