# Generated by Django 2.2.5 on 2019-11-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20191120_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar',
            new_name='Avatar',
        ),
    ]
